# Generated by Django 4.2.9 on 2024-01-19 10:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('collapsible_sections', wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('faqs', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.CharBlock()), ('answer', wagtail.blocks.TextBlock())])))]))], use_json_field=True)),
                ('searchable_faqs', wagtail.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FeaturePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('icon', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('demo', wagtail.fields.StreamField([('demo', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.TextBlock())]))], use_json_field=True)),
                ('call_to_action', wagtail.fields.StreamField([('call_to_action', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_section', wagtail.fields.StreamField([('call_to_action', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())])), ('feature', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock()), ('call_to_action', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())]))])), ('demo', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.TextBlock())]))], default=[{'type': 'feature', 'value': {'call_to_action': {'text': 'Learn More', 'url': '/features/'}, 'description': 'Discover the amazing features that make NexusTech stand out.', 'icon': 'fa-cogs', 'title': 'Powerful Features'}}, {'type': 'call_to_action', 'value': {'text': 'Join Now', 'url': '/signup/'}}], use_json_field=True)),
                ('sticky_navigation_menu', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())]))], default=[{'type': 'link', 'value': {'text': 'Home', 'url': '/'}}], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PricingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('pricing_plans', wagtail.fields.StreamField([('pricing_plan', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('price', wagtail.blocks.DecimalBlock()), ('features', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock()))]))], use_json_field=True)),
                ('feature_comparison_table', wagtail.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestimonialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('testimonial_text', wagtail.fields.RichTextField()),
                ('image', models.ImageField(upload_to='testimonials/')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
